# Content for header / footer
title: Ashterism
author: Musings by Ash
description: A collection of thoughts and experiences on Astronomy, Hiking, Sustainability, and the like
# email: ""
url: https://ashterism.com

theme: minima
markdown: kramdown

timezone: Etc/UTC # GitHub uses UTC. This is to force dev environment to match
future: false # GitHub Pages will publish future posts if this isn't set to false

# Minima variables
github_username:   ashterism
instagram_username: asherture
rss: rss

show_excerpts: false

